[build]
  command = "npm install"
  publish = "."

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    
[[headers]]
  for = "*.js" 
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/assets/*"
  to = "/public/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
